version: "3.8"
services:
  hospital:
    build: ./hospital
    ports:
      - "5000:5000"
    restart: on-failure
    links: 
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - datavolume:/var/lib/mysql
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
volumes:
  datavolume:

 